#!/usr/bin/env bash
# helpers/.local/bin/cloud-mount
# Usage: cloud-mount <remote_name> <action: start|stop|status|enable|disable>

REMOTE=$1
ACTION=${2:-start}

if [[ -z "$REMOTE" ]]; then
    echo "Usage: cloud-mount <remote_name> [action]"
    echo "Actions: start (default), stop, status, enable, disable"
    exit 1
fi

case "$ACTION" in
    start|stop|status|enable|disable)
        systemctl --user "$ACTION" "rclone-mount@${REMOTE}.service"
        ;;
    *)
        echo "Unknown action: $ACTION"
        exit 1
        ;;
esac
