# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Use custom palette
palette = "catppuccin_mocha"

# Configure the format
format = """
$directory$git_branch$git_status$fill$cmd_duration$aws${custom.gcloud}$terraform$kubernetes$nix_shell$python
$character"""

# Move these to the right (if supported by terminal/shell)
right_format = ""

[directory]
style = "bold lavender"
# style = "bg:lavender fg:surface0"
truncation_length = 0
truncate_to_repo = false
format = "[ $path ]($style) "

[fill]
symbol = " "

[git_branch]
symbol = " "
style = "bold mauve"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"
format = '([\[$all_status$ahead_behind\]]($style) )'

[aws]
symbol = "a:"
style = "bold peach"
format = '[$symbol:$profile]($style) '


[gcloud]
disabled = false
symbol = "g"
style = "bold blue"
format = '[$symbol:$active]($style) '
detect_files = ['.envrc']             
detect_folders = [ ]

[kubernetes]
symbol = "k"
style = "bold blue"
format = '[$symbol:$context: ($namespace)]($style) '

[nix_shell]
symbol = "nix"
style = "bold blue"
format = "[$symbol]:($style) "

[terraform]
disabled = false
symbol = "tw"
style = "bold mauve"
format = '[$symbol:$workspace]($style) '
detect_folders = [ ]

[python]
symbol = "py"
style = "bold yellow"
format = '[$symbol:$version:($virtualenv)]($style) '
detect_extensions = ['py']
detect_files = ['.python-version', 'pyproject.toml', 'setup.py', 'requirements.txt', 'Pipfile', 'tox.ini']
detect_folders = []

[cmd_duration]
min_time = 5_000
style = "bold surface2"
format = "[$duration]($style) "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"