#!/usr/bin/env python3
import os
import sys


def load_yaml(path):
    try:
        import yaml
        with open(path) as fh:
            return yaml.safe_load(fh) or {}
    except ImportError:
        data = {}
        in_profiles, current_profile = False, None
        if os.path.isfile(path):
            with open(path) as fh:
                for line in fh:
                    raw = line.split('#')[0].strip()
                    if not raw:
                        continue
                    indent = len(line) - len(line.lstrip())
                    if indent == 0:
                        in_profiles, current_profile = False, None
                    if raw.endswith(':'):
                        k = raw[:-1].strip()
                        if k == 'profiles':
                            in_profiles = True
                            data['profiles'] = {}
                        elif in_profiles:
                            current_profile = k
                            data['profiles'][current_profile] = []
                    elif ':' in raw:
                        k, v = raw.split(':', 1)
                        data[k.strip()] = v.strip().strip('\"').strip("'")
                    elif raw.startswith('-') and in_profiles and current_profile:
                        data['profiles'][current_profile].append(
                            raw[1:].strip().strip('\"').strip("'"))
        return data


def load_secrets(path):
    secrets = {}
    if os.path.isfile(path):
        with open(path) as fh:
            for line in fh:
                line = line.split('#')[0].strip()
                if not line:
                    continue
                if line.startswith('export '):
                    line = line[7:].strip()
                if '=' in line:
                    k, v = line.split('=', 1)
                    secrets[k.strip()] = v.strip().strip('\"').strip("'")
    return secrets


cfg = load_yaml('config.yml')
local_cfg = load_yaml('local.yml') if os.path.isfile('local.yml') else {}
cfg.update(local_cfg)

profile = os.environ.get('DOTFILES_PROFILE') or cfg.get('profile', 'standard')
packages = cfg.get('profiles', {}).get(profile, [])

if len(sys.argv) < 2:
    print("Usage: parse_config.py [profile|packages|env|info]")
    sys.exit(1)

action = sys.argv[1]

if action == 'profile':
    print(profile)

elif action == 'packages':
    print(" ".join(packages))

elif action == 'env':
    print('# Generated by justfile parse_config.py. Do not edit.')
    print(f'export DOTFILES_PROFILE="{profile}"')
    for k, v in cfg.items():
        if k != 'profiles' and not isinstance(v, (dict, list)):
            print(f'export DOTFILES_{k.upper()}="{v}"')

    secrets = load_secrets('../.secrets')
    if secrets:
        print('\n# Secrets merged from ../.secrets')
        for k, v in secrets.items():
            print(f'export {k}="{v}"')

elif action == 'info':
    print(f'Active Profile:  {profile}')
    print(f'Exposed Theme:   {cfg.get("theme", "default")}')
    print(f'Exposed Font:    {cfg.get("font_family", "default")} (size: {
          cfg.get("font_size", "default")})')
    print('Packages to Link:')
    for pkg in packages:
        print(f'  - {pkg}')
    secrets = load_secrets('../.secrets')
    if secrets:
        print(
            f'Secrets detected (will be merged from ../.secrets): {list(secrets.keys())}')

else:
    # Allow querying arbitrary configuration keys
    if action in cfg:
        print(cfg[action])
    else:
        print(f"Error: Unknown action or config key '{
              action}'", file=sys.stderr)
        sys.exit(1)
