#!/usr/bin/env sh
# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# -- mouse settings --
# center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

# disable specific apps
yabai -m rule --add app="^Calculator$" manage=off

## set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier cmd

# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

echo "yabai configuration loaded.."
