[all]
localhost ansible_connection=local

[single_boards]
# Example host:
# pi-node-01.local dotfiles_profile=lean

[workstations]
# Example hosts:
# mbp-work.local dotfiles_profile=mac_workstation
# dev-box.local dotfiles_profile=standard
