return {
    'nvim-treesitter/nvim-treesitter',
    branch = 'master',
    build = ':TSUpdate',
    opts = {
        ensure_installed = {
            'http',
            'bash',
            'make',
            'c',
            'go',
            'python',
            'lua',
            'luadoc',
            'kconfig',
            'helm',
            'nix',
            'regex',
            'jinja',
            'hcl',
            'sql',
            'html',
            'json',
            'yaml',
            'toml',
            'markdown',
            'markdown_inline',
            'diff',
            'vim',
            'vimdoc',
        },
        auto_install = true,
        highlight = { enable = true },
        indent = { enable = true },
        incremental_selection = {
            enable = true,
            keymaps = {
                init_selection = '<CR>',
                node_incremental = '<CR>',
                scope_incremental = '<Tab>',
                node_decremental = '<BS>',
            },
        },
    },
    config = function(_, opts)
        require('nvim-treesitter').setup(opts)
    end,
}
